<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Update Profile Sukses</name>
   <tag></tag>
   <elementGuidId>8002889f-564e-4cd6-9993-7c8142989fb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/div[2]/div/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.alert.alert-primary.mt-4.ml-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>82b65976-8221-4c8b-92ff-84f32ec2ff14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert alert-primary mt-4 ml-5</value>
      <webElementGuid>bb886759-da12-4b99-9252-41cbf614ee50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>54f8b594-076b-491f-9251-6bcb863b07b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Update Profile Sukses</value>
      <webElementGuid>a9cda56e-d5d6-410f-a731-0d8ab203d1b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-10 col-lg-10&quot;]/div[@class=&quot;card shadow mb-4&quot;]/div[@class=&quot;col-md-10 col-sm-12 col-xs-12 ml-5 mt-5&quot;]/div[@class=&quot;alert alert-primary mt-4 ml-5&quot;]</value>
      <webElementGuid>831f3f58-2635-4b1d-ae57-02e6bd15aa87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div[2]/div/div[3]/div</value>
      <webElementGuid>46c08edc-55d9-4ae7-8f39-65f96baf0ebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update'])[1]/following::div[2]</value>
      <webElementGuid>13b33c45-3f4d-49a6-8eb9-832f65067cfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ganti Foto Profile'])[1]/following::div[4]</value>
      <webElementGuid>42f8be5d-e65c-4aff-9c6c-c727773f829c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Faiz Nurullah'])[1]/preceding::div[1]</value>
      <webElementGuid>1f901ee2-db1d-4839-9a59-04436b113fc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div</value>
      <webElementGuid>cbdf4fb2-86f4-4a19-a02b-3f000c2009b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Update Profile Sukses' or . = 'Update Profile Sukses')]</value>
      <webElementGuid>7595174f-c38c-4ac1-a7ae-e074fa618474</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
