<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jumlah_jumlah</name>
   <tag></tag>
   <elementGuidId>9e2b1a2f-24f6-41e0-b5dc-e2ddaf3b70a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;jumlah&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='jumlah']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3784ef40-b864-4506-977d-d00a251da9dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cca09118-2e3a-4a82-b47d-df8fc44baae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>eff25f9b-bc85-44f6-954e-a70c03aec26e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jumlah</value>
      <webElementGuid>71454510-58a0-44bb-aebe-7eaaabb513c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Jumlah...</value>
      <webElementGuid>1e99d65d-174b-403f-8d2b-49901340986e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>870</value>
      <webElementGuid>5df2a040-170b-4bc2-8f25-ef5984f8e98a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;card shadow  ml-4 mr-4&quot;]/form[1]/div[@class=&quot;row ml-5 mb-2 mt-3&quot;]/div[@class=&quot;col-md-6&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>de0cdf45-9afd-4d93-baca-cd8dfc3f2826</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='jumlah']</value>
      <webElementGuid>01b4803a-234b-4456-9ca3-01d9d032660f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/form/div/div/input</value>
      <webElementGuid>4e5595f7-a67e-4928-8d97-569cdcd5ecc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b41fb0c2-abc2-42a8-a5b2-e5bbf801697a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'jumlah' and @placeholder = 'Jumlah...']</value>
      <webElementGuid>bb74ad09-7f48-462f-a63b-5ae2a5f82dc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
